---
title: "Empowering the use of preprints in ecology and evolution: an exploration of the first 1000 *EcoEvoRxiv* preprints"
bibliography: ../bib/refs.bib
csl: ../bib/nature.csl
format:
  docx:
    reference-doc: ../bib/template.docx
editor_options: 
  chunk_output_type: console
execute:
  freeze: auto  # re-render only when source changes
  cache: false
  echo: false
  warning: false
  error: false
  include: true
crossref:
  fig-title: 'Figure'
  fig-labels: arabic
  title-delim: "-"
  fig-prefix: "Figure"
  tbl-prefix: "Table"
---

Authors: Daniel W.A. Noble, Malgorzata Lagisz, Hackathon Participants, Shinichi Nakagawa

# Introduction

Publishing preprints -- papers communicating non-peer-reviewed research findings -- is now an entrenched practice across a multitude of scientific disciplines in many countries [@Ginsparg2011]. While preprint use in biology has had a slower uptake [@Berg2016], in ecology and evolution, new discipline specific preprint servers, such as *EcoEvoRxiv*, provide a means by which ecologists and evolutionary biologists can disseminate research findings. Such practices promote open science (e.g., ensuring papers are open access) and facilitate the rapid sharing of new discoveries that can have significant impacts on fundamental and applied knowledge globally (e.g., conservation outcomes). 

Preprints attempt to break down barriers to scientific publishing by: 1) increasing the speed, visibility and output of research findings; 2) encouraging constructive and critical feedback from a research community; 3) helping establish precedence of research findings; and 4) removing financial barriers to publication [@Proulx2013 and others]. Importantly, *EcoEvoRxiv* is a community driven preprint server that has paved the way for new initiatives that attempt to further break down barriers to scientific dissemination and improve research practice, including accepting multilingual preprints (i.e., Spanish and Portuguese), recognising and accepting registered reports and promoting the use of peer review and community discussion to improve the quality of preprints and speed up their peer-reviewed publication (e.g., Peer Community In -- PCI). 

Preprint servers, such as *EcoEvoRxiv*, can empower researchers to make their findings more accessible, open and transparent but only if they are used, and used well. Significant barriers to preprint use still exist globally – from worry about XXX to XXX. Nonetheless, we lack a systematic understanding of the factors that influence preprint use in ecology and evolution which can help inform future initiatives and help us begin to break down barriers to their use in our field. Here, we explore the first 1000 preprints uploaded to *EcoEvoRxiv* to understand preprint practices and use in our field, focusing on our attention on understanding: 1) how long it takes for a preprint to become published, and how many preprints remain unpublished; 2) what countries make use of preprints; 3) how career stage and gender impact preprint use; 4) whether data and code are more likely to be shared in preprints; and 5) the extent to which authors make use of preprint servers for registered reports and community driven peer review. 

# References